services:
  nginx:
    container_name: graffiti-nginx
    image: nginx:stable-alpine-slim
    ports:
      - 443:443
    environment:
      DOMAIN: ${DOMAIN}
      COUCHDB_DOMAIN: ${COUCHDB_DOMAIN}
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    volumes:
      - ./server/config/nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - /etc/letsencrypt/:/etc/letsencrypt/:ro

  graffiti-pod:
    entrypoint: ["npm", "run", "start:prod"]
