volumes:
  graffiti-data:
  graffiti-couchdb-config:

services:
  graffiti-pod:
    container_name: graffiti-pod
    build: .
    volumes:
      - ./server/src:/server/src
      - ./server/tsconfig.json:/server/tsconfig.json
      - ./server/vitest.config.ts:/server/vitest.config.ts
      - ./.env:/server/.env
      - ./.secrets.json:/.secrets.json
    environment:
      - USE_COUCHDB=true
    depends_on:
      - couchdb

  couchdb:
    image: couchdb:latest
    container_name: graffiti-couchdb
    volumes:
      - graffiti-data:/opt/couchdb/data
      - graffiti-couchdb-config:/opt/couchdb/etc
      - ./server/config/couchdb/10-single-node.ini:/opt/couchdb/etc/local.d/10-single-node.ini
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    restart: unless-stopped
